### ISSUE TITLE
Initial research on securely handle Secrets

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/go-k8s-infra#108]
Hi Nader, see EPIC https://github.com/k8-proxy/go-k8s-infra/issues/104, we are looking for a solution on secret management for all platforms that we support (AWS, ESXi, GCP and Azure is the next one). 

Please start by:
- See options in channel: cloud-sdk-secrets
- review this option too: https://www.vaultproject.io/docs/secrets

We would like to start doing some research on the possible options and discussing with the team.

**Comment by GINAGC** [comment]
fyi @mahnouman

**Comment by naderaly** [comment]
Initial Findings posted in slack : https://glasswall-solutions.slack.com/archives/C023L60PTNH/p1626160333012000

**Comment by GINAGC** [comment]
Closing, for now, secrets management will be reviewed as part of the BYOC project.
