### ISSUE TITLE
ZIP with files with issues inside returns status 200

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/go-k8s-infra#109]
endpoints that accept and rebuild ZIP should not return status 200 in case inside the zip file are files that are not processable or with issues.
In classic endpoint return a zip with all clean files + an error.html file instead of the file with issue (status 207)
In Minio endpoint returns a zip with all the cleaned files - the file with issue. (status 200)

we need to include an error report inside the zip for the files that can not be rebuild.

**Comment by GINAGC** [comment]
@mahnouman who can take this one?

**Comment by mohitsengarr** [comment]
@GINAGC please assign this to go-Minio team.

**Comment by GINAGC** [comment]
@mohitsengarr we would like that you give a first pass and comment on what is the problem.

**Comment by mohitsengarr** [comment]
@GINAGC problem is minio is not having `ErrorReport.html` in the zip in case of any zip files is failed to process. While classic version does. So, minio needs to add `ErrorReport.html` in the returned zip.

**Comment by GINAGC** [comment]
ok, then I will check with @mahnouman to assign this.

**Comment by ibrahimk9000** [comment]
@GINAGC 
can you move this issue to k8-porcess

**Comment by GINAGC** [comment]
Issue moved to [k8-proxy/go-k8s-process #121](https://github.com/k8-proxy/go-k8s-process/issues/121) via [**ZenHub**](https://www.zenhub.com/)
