### ISSUE TITLE
Document an issue where the rebuild pod that complete it task are not getting delete

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#110]
Please create an issue documenting your observation that the rebuild pod that complete it task are not getting delete. Please add as much details as possible to help whom it will be assigned to investigate it further.

**Comment by himanshu2464** [comment]
when we execute the f2f test with 100 threads or 50threads, on the API  for 1000 files, the rebuild pods are getting deleted on the spot after completing the task, it took little time to get terminated. and after completion of the test rebuild pods count should be the same as the pods count that we have defined. For example, we have a default pod count = 25 so after completion of the test with 100 threads, it should back to the 25 pods count, but instead, it is not.

**Comment by mahnouman** [comment]
@himanshu2464 please open a new issue, with the details, screenshots, preproduction steps and so on.. please explain this: but instead, it is not.
Like is it higher or lower, fixed number or so

Please do so in a new issue.

**Comment by himanshu2464** [comment]
instead, it is a higher number instead of a 25 pod count that is the default.
