### ISSUE TITLE
mpg files passes as file_type_not_supported

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/go-k8s-infra#114]
video mpg file passes as not supported, while in classic sdk it passes as file-needs-no-modifications. however the file itself passed in hd3 with all the cleaned files. file with `name: metaxas-keller-Bell_63.9MB.mpg` is on slack.

**Comment by GINAGC** [comment]
@ibrahimk9000 how this issue is going?

**Comment by GINAGC** [comment]
@ibrahimk9000 to update on the latest findings on this one.

**Comment by ibrahimk9000** [comment]
this issue is related to the kubernete resources configuration  , i tested the mpg file in the docker setup in my local machine and it works as expected

**Comment by GINAGC** [comment]
@himanshu2464 can you take a look to this?

**Comment by himanshu2464** [comment]
@ibrahimk9000 can you please provide me the file in order to test.

**Comment by himanshu2464** [comment]
@ibrahimk9000 @GINAGC 
the  files that Ibrahim send to me that mpg and it is successfully rebuild 

![image](https://user-images.githubusercontent.com/45463238/125129963-ce842500-e11d-11eb-835f-25654e9ffc97.png)

![image](https://user-images.githubusercontent.com/45463238/125130032-ecea2080-e11d-11eb-8bf2-37eeca41b657.png)

**Comment by GINAGC** [comment]
@Lestat06 please review this.

**Comment by Lestat06** [comment]
@himanshu2464 please try the IP with scenario jp-test that u have in ur f2f vm and u will see the issue

**Comment by himanshu2464** [comment]
@Lestat06  if it is processable with Api directly then it should also work with f2f as well.

let me test it with F2F as well today.

**Comment by himanshu2464** [comment]
@Lestat06 I got the problem the issue was the memory limit issues in the processing pod.
so in order to fix this, I updated the helm charts of go-k8s-infra with the environment variable PROCESS_POD_MEMORY_LIMIT 
the limit was 500Mi and I change the limit to 1000Mi so that it will not run out of the resource.

@GINAGC @Lestat06 @mahnouman  i will generate a PR with this variable in Helm charts so that it will work automatically in the next AMI build.

**Comment by himanshu2464** [comment]
@GINAGC @mahnouman 
this is the PR for the fix. 
https://github.com/k8-proxy/go-k8s-infra/pull/130

**Comment by Lestat06** [comment]
This one I cant test from develop branch due to Incident we have. will have to wait till is merged or incident fixed.
INC https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/71

**Comment by Lestat06** [comment]
this is fixed now in develop-golang. files get treated as file-needs-no-modification
![image](https://user-images.githubusercontent.com/6232283/126319746-ae806448-19af-4da5-bbf7-dec64012f5c1.png)
![image](https://user-images.githubusercontent.com/6232283/126319821-06542c2c-e40f-4d3e-89a2-8c39cff12d63.png)
