### ISSUE TITLE
Multi rebuild pods launched for a single file rebuilt

### ISSUE THREAD

**Issue by naderaly** [k8-proxy/go-k8s-infra#116]
To replicate the issue:
1- run f2f with 1 thread by time 
2- check dashboard 

![image](https://user-images.githubusercontent.com/58347752/124305180-07902880-db65-11eb-8738-ac9a922e1f89.png)

**Comment by azopat** [comment]
@naderaly  @mahnouman  i checked but couldn't reproduce the problem. It worked well for me
@naderaly  do you have it all the time ?

**Comment by naderaly** [comment]
@azopat happened with me , mahmoud & @Lestat06 also , lets arrange a meeting tomorrow trying to reproduce it

**Comment by mahnouman** [comment]
Work on this issue would be on https://github.com/k8-proxy/go-k8s-infra/issues/123

**Comment by GINAGC** [comment]
Closing with https://github.com/k8-proxy/go-k8s-controller/issues/35
