### ISSUE TITLE
PDF file fails with error 400 : INTERNAL_ERROR

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/go-k8s-infra#117]
this file can be processed in classic sdk and in running locally with docker
[20090707-WAF-v0.1.pdf](https://github.com/k8-proxy/go-k8s-infra/files/6756756/20090707-WAF-v0.1.pdf) 

Marking as P2 since so far is 1 PDF.

**Comment by haitham911** [comment]
its work in my local machine and i test it in Kubernetes  i found that cli that rebuild file  end with
 error unknown exit status code : 137,
![2021-07-05 16_52_47-Jaeger UI](https://user-images.githubusercontent.com/10202798/124594663-5d641980-de60-11eb-9815-4914d86ba0ae.png)
this problem of pod resources memory

**Comment by GINAGC** [comment]
duplicated with https://github.com/k8-proxy/go-k8s-infra/issues/103
