### ISSUE TITLE
Cant access the services in their ports in Kompliant CK8s golang

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/go-k8s-infra#118]
the below services cant be accesed in ck8s version of golang
RabbitMQ UI | 15672
Minio | 9000
jaeger | 9001
Kubernetes Dashboard | 9090

**Comment by GINAGC** [comment]
@Lestat06 to retest with new deployment

**Comment by Lestat06** [comment]
services still cannt be accessed

**Comment by GINAGC** [comment]
@naderaly can you research on this? was this in purpose to not expose these services?

**Comment by GINAGC** [comment]
this is duplicated
