### ISSUE TITLE
instance is running with 1 rebuild-api pod in ck8s-golang

### ISSUE THREAD

**Issue by Lestat06** [k8-proxy/go-k8s-infra#119]
there should be 4 rebuild-api pods running in golang version
u can check this by ssh into the machine and run `kubectl get pods -n icap-adaptation`

![image](https://user-images.githubusercontent.com/6232283/124468037-eadc3680-dd98-11eb-960d-e745dc9e2dea.png)

**Comment by naderaly** [comment]
@GINAGC Issue fixed in the server provided by @Lestat06 by editing the deployment and configuring the correct cpu/memory limits and also the replica count.
but I don't know if this is already added to the process of building the AMI

**Comment by naderaly** [comment]
![image](https://user-images.githubusercontent.com/58347752/124483124-47941d00-ddaa-11eb-9840-9393597259e5.png)

**Comment by naderaly** [comment]
- Login to server and switch to root user

**sudo su -**

- change directory and clone **go-k8s-infra** repo
**cd /home/ubuntu; git clone https://github.com/k8-proxy/go-k8s-infra.git**
**cd go-k8s-infra/services/**

- Delete servicesv2 
**helm delete servicesv2 -n icap-adaptation**

- Delete all rebuild pods 
**kubectl get pods -n icap-adaptation | grep rebuild-pod | cut -d' ' -f 1 | xargs kubectl delete pod -n icap-adaptation**

- wait till all pods are terminated (use the command multiple times to update output)
**kubectl get pods -n icap-adaptation | grep rebuild-pod**


- Edit rebuild-api deployment by running:

**kubectl edit deploy rebuild-api -n icap-adaptation**

- Scroll down in the file and find resources and edit the file as shown in the screenshot:

![image](https://user-images.githubusercontent.com/58347752/124501998-e0cf2d80-ddc2-11eb-84ec-9d465dc0ecf2.png)         resources:
  **limits:
    cpu: 1500m
    memory: 2Gi
  requests:
    cpu: "1"
    memory: 1000Mi**

- Also find replicas under spec and edit number of replicas to be 4:
![image](https://user-images.githubusercontent.com/58347752/124502305-8387ac00-ddc3-11eb-874f-499ac755e0ba.png)

- Save the file and exit

- Verify that you have 4 replicas of rebuild-api (wait couple of mins)
**kubectl get deploy -n icap-adaptation**

- Make sure your current working directory in **/home/ubuntu/go-k8s-infra/services** and start servicesv2
**helm upgrade servicesv2 --install . --namespace icap-adaptation**

- Wait up to 5 mins to have all 25 rebuild pods ready, verify by running 
kubectl get pods -n icap-adaptation | grep rebuild-pod

**Comment by naderaly** [comment]
@GINAGC

**Comment by GINAGC** [comment]
@Lestat06 to validate once that we have new AMIs, since Pranay has automated the steps above.

**Comment by Lestat06** [comment]
this is fixed in the new deployment and automated. 4 rebuild-apis are there
![image](https://user-images.githubusercontent.com/6232283/124722457-5c87c200-df0a-11eb-8562-638befd04cf0.png)
