### ISSUE TITLE
after complication of the f2f, pods counts of rebuild pods should be same as it is define in deployment but instead it is higher number.

### ISSUE THREAD

**Issue by himanshu2464** [k8-proxy/go-k8s-infra#121]

**Comment by himanshu2464** [comment]
when we execute the f2f test with 100 threads or 50threads, on the API for 1000 files, the rebuild pods are getting deleted on the spot after completing the task, it took little time to get terminated. and after completion of the test rebuild pods count should be the same as the pods count that we have defined. For example, we have a default pod count = 25 so after completion of the test with 100 threads, it should back to the 25 pods count, but instead, it is higher number of counts are there.

**Comment by himanshu2464** [comment]
![image](https://user-images.githubusercontent.com/45463238/124493177-f3e9f980-ddd2-11eb-94da-2baaf16bd1d6.png)
run test with 50 threads and it is completed and still i see the rebuild-pods to 40 instead it should be 25 .
![image](https://user-images.githubusercontent.com/45463238/124493334-21cf3e00-ddd3-11eb-90be-e13ebffff3d2.png)

**Comment by mahnouman** [comment]
Work on this issue would be on https://github.com/k8-proxy/go-k8s-infra/issues/123

**Comment by GINAGC** [comment]
Closing with https://github.com/k8-proxy/go-k8s-controller/issues/35
