### ISSUE TITLE
F2F is broken it is giving error when configuring the endpoint

### ISSUE THREAD

**Issue by himanshu2464** [k8-proxy/go-k8s-infra#126]
when we do the configuration of IP in F2F and swagger for endpoint it is giving the following error.

![image](https://user-images.githubusercontent.com/45463238/125450680-f64ffc9f-a1d0-43e3-8f84-8a1562abdd25.png)

![image](https://user-images.githubusercontent.com/45463238/125450739-ad91dccd-d35c-48f5-8886-21d92d564782.png)

this happens with the AMI we build from develop branch.

**Comment by GINAGC** [comment]
closing as duplicated https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/71
