### ISSUE TITLE
minio-errors

### ISSUE THREAD

**Issue by haitham911** [k8-proxy/go-k8s-infra#134]
when I test using f2f  to send file to CDR-platform ,the minio get down and when it restart the process failed with this error
{"level":"error","error":"error uploading file from minio : The specified bucket does not exist","time":"2021-07-17T10:54:34Z","message":"error adaptationRequest consumer Failed to process message"}
we need when minio restart did not lose files and bucket that on its storge 
It's important that when pod restart  retain everything of the previous pod.

**Comment by himanshu2464** [comment]
buckets and all data in buckets get lost because minio deployment does not have persistence storage. 
so here is the PR with minio deployment with persistence storage .

https://github.com/k8-proxy/vmware-scripts/pull/160

**Comment by GINAGC** [comment]
@naderaly please test this one with the latest release.

**Comment by naderaly** [comment]
@GINAGC This is tested and confirmed data on minio are persistent , this is tested against deleting pods and also restarting minio deployment
