### ISSUE TITLE
minio connection issues between pods .

### ISSUE THREAD

**Issue by himanshu2464** [k8-proxy/go-k8s-infra#21]
the process to reproduce:
follow the instruction to setup .
https://github.com/k8-proxy/vmware-scripts/blob/minio/packer/target/icap-server/setup.sh

clone https://github.com/k8-proxy/go-k8s-infra/tree/azopat-tmp

and once the services and minio and all is setup.
check the logs of minio pods 

kubectl logs -f minio-ss-0-0 -n minio

API: SYSTEM()
Time: 17:05:32 UTC 04/02/2021
Error: lookup minio-ss-0-0.minio-hl.minio.svc. on 10.43.0.10:53: no such host (*net.DNSError)
       host=minio-ss-0-0.minio-hl.minio.svc., elapsedTime=2 hours elapsed
       5: cmd/endpoint.go:469:cmd.Endpoints.UpdateIsLocal()
       4: cmd/endpoint.go:653:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:372:cmd.createServerEndpoints()
       2: cmd/server-main.go:142:cmd.serverHandleCmdArgs()
       1: cmd/server-main.go:418:cmd.serverMain()

API: SYSTEM()
Time: 17:05:32 UTC 04/02/2021
Error: lookup minio-ss-0-1.minio-hl.minio.svc. on 10.43.0.10:53: no such host (*net.DNSError)
       host=minio-ss-0-1.minio-hl.minio.svc., elapsedTime=2 hours elapsed
       5: cmd/endpoint.go:469:cmd.Endpoints.UpdateIsLocal()
       4: cmd/endpoint.go:653:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:372:cmd.createServerEndpoints()
       2: cmd/server-main.go:142:cmd.serverHandleCmdArgs()
       1: cmd/server-main.go:418:cmd.serverMain()

API: SYSTEM()
Time: 17:05:32 UTC 04/02/2021
Error: lookup minio-ss-0-2.minio-hl.minio.svc. on 10.43.0.10:53: no such host (*net.DNSError)
       host=minio-ss-0-2.minio-hl.minio.svc., elapsedTime=2 hours elapsed
       5: cmd/endpoint.go:469:cmd.Endpoints.UpdateIsLocal()
       4: cmd/endpoint.go:653:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:372:cmd.createServerEndpoints()
       2: cmd/server-main.go:142:cmd.serverHandleCmdArgs()
       1: cmd/server-main.go:418:cmd.serverMain()

API: SYSTEM()
Time: 17:05:32 UTC 04/02/2021
Error: lookup minio-ss-0-3.minio-hl.minio.svc. on 10.43.0.10:53: no such host (*net.DNSError)
       host=minio-ss-0-3.minio-hl.minio.svc., elapsedTime=2 hours elapsed
       5: cmd/endpoint.go:469:cmd.Endpoints.UpdateIsLocal()
       4: cmd/endpoint.go:653:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:372:cmd.createServerEndpoints()
       2: cmd/server-main.go:142:cmd.serverHandleCmdArgs()
       1: cmd/server-main.go:418:cmd.serverMain()

and when you submit the file using c-icap-client

and check the logs of service logs 

root@ip-172-31-17-217:/home/ubuntu# kubectl logs -f srv1-7cc64f6f47-592zg -n icap-adaptation
2021/04/02 15:07:14 [*] Waiting for messages. To exit press CTRL+C
2021/04/02 15:17:41 Received a message for file: d1ea3622-a05a-4068-82ea-a0dd548266c9
Get "https://minio-ss-0-0.minio-hl.minio.svc.cluster.local:9000/sourcefiles/?location=": dial tcp 10.42.0.34:9000: connect: connection refused
2021/04/02 15:17:41 Failed to process message: Get "https://minio-ss-0-0.minio-hl.minio.svc.cluster.local:9000/sourcefiles/?location=": dial tcp 10.42.0.34:9000: connect: connection refused

**Comment by azopat** [comment]
@himanshu2464  please try to use this procedure - https://github.com/minio/charts#minio-legacy-docs and deploy minio in another namespace in that machine.
If it works then we will switch to it (instead of using the operator).
Once deployed please check if you can create a bucket etc

**Comment by himanshu2464** [comment]
okay, I will deploy it.

**Comment by himanshu2464** [comment]
the logs of the service is not getting an proper minio endpoint  with minio operator.

root@ip-172-31-45-230:~/go-k8s-infra/services# kubectl logs -f srv1-998ddddd9-2wrcl -n icap-adaptation
2021/04/05 14:41:17 [*] Waiting for messages. To exit press CTRL+C
2021/04/05 14:45:45 Received a message for file: 26d89551-69c2-4cbd-8182-8521c12e7f60
Get "http://minio-endpoint.minio.svc.cluster.local:9000/sourcefiles/?location=": dial tcp: lookup minio-endpoint.minio.svc.cluster.local on 10.43.0.10:53: no such host
2021/04/05 14:45:45 Failed to process message: Get "http://minio-endpoint.minio.svc.cluster.local:9000/sourcefiles/?location=": dial tcp: lookup minio-endpoint.minio.svc.cluster.local on 10.43.0.10:53: no such host

and in minio logs 

Waiting for a minimum of 4 disks to come online (elapsed 8s)


API: SYSTEM()
Time: 14:41:03 UTC 04/05/2021
Error: Marking https://minio-ss-0-3.minio-hl.minio.svc.cluster.local:9000/minio/storage/export1/v28 temporary offline; caused by Post "https://minio-ss-0-3.minio-hl.minio.svc.cluster.local:9000/minio/storage/export1/v28/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio-ss-0-3.minio-hl.minio.svc.cluster.local on 10.43.0.10:53: no such host (*fmt.wrapError)
       6: cmd/rest/client.go:124:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:132:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:422:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:416:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:325:cmd.loadFormatErasureAll.func1()
       1: pkg/sync/errgroup/errgroup.go:122:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 14:41:03 UTC 04/05/2021
Error: Marking https://minio-ss-0-2.minio-hl.minio.svc.cluster.local:9000/minio/storage/export0/v28 temporary offline; caused by Post "https://minio-ss-0-2.minio-hl.minio.svc.cluster.local:9000/minio/storage/export0/v28/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio-ss-0-2.minio-hl.minio.svc.cluster.local on 10.43.0.10:53: no such host (*fmt.wrapError)
       6: cmd/rest/client.go:124:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:132:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:422:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:416:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:325:cmd.loadFormatErasureAll.func1()
       1: pkg/sync/errgroup/errgroup.go:122:errgroup.(*Group).Go.func1()

**Comment by himanshu2464** [comment]
after deploying the standalone minio with helm charts, and configure the service to use this standalone minio endpoint, it works successfully.

**Comment by himanshu2464** [comment]
https://github.com/k8-proxy/go-k8s-infra/tree/himanshu-tmp 
this is the PR.

Done.
