### ISSUE TITLE
Compliant Kubernetes

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#25]
We need to assemble the setup into the [Compliant Kubernetes](https://github.com/k8-proxy/k8s-compliant-kubernetes), please investigate and figure out what it would take for this to work.

Please check how the cloud SDK team followed the same:
https://github.com/k8-proxy/k8s-compliant-kubernetes/blob/main/.github/workflows/complaint-k8s-CloudSDK.yaml

**Comment by GINAGC** [comment]
this was already done by Samarth, closing for now.
