### ISSUE TITLE
Test and adjust the code to test the new Process pod

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#28]
Please do the following changes:
Only GW repos and dockerhub is referenced or placeholders, but not personal repositories.
Please test the process pod code currently in the develop branch.
Make sure the process pod kills itself after a it process a file and that controller is starting a new process pod right away.

**Comment by mahnouman** [comment]
Hello @ibrahimk9000 please work with @himanshu2464 to trace the issue we faces in the demo session.

**Comment by himanshu2464** [comment]
the issues are identified and the fix is applied, and now the file is been processed and getting a response.
Done!

**Comment by himanshu2464** [comment]
the issues are identified and the fix is applied, and now the file is been processed and getting a response.
Done!
