### ISSUE TITLE
Replace personal repos with the official one

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#34]
Please scan through the repo and replace the personal references like dockerhub or forks with the official ones, in case an official substitue is not around, please add a placeholder and mention here in the repo, this is applicable to the develop branch, list of official dockerhub repos is:
https://hub.docker.com/repository/docker/k8serviceaccount/go-k8s-process
https://hub.docker.com/repository/docker/k8serviceaccount/go-k8s-controller
https://hub.docker.com/repository/docker/k8serviceaccount/go-k8s-srv1
https://hub.docker.com/repository/docker/k8serviceaccount/go-k8s-srv2

**Comment by GINAGC** [comment]
this is done
