### ISSUE TITLE
Document AMI building process

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#36]
Please add the following information to the readme file of this repository:

1. Add a link to the existing AMI in a table.
2. Provide much details into how to recreate AMI, referencing YAML file.
3. Add as much comments to the YAML file producing the AMI as possible.
4. Make sure no personal repositories are used either in documentation of the actual code. the branch of interest in this repository is the development branch.

**Comment by azopat** [comment]
This is done

**Comment by GINAGC** [comment]
@mahnouman please confirm if this can be closed or someone else will test it.

**Comment by mahnouman** [comment]
Hello @GINAGC we can close it for now. We will revisit when the guys are creating a new workflow
