### ISSUE TITLE
Jaeger integration

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#50]
Integration of Jaeger, so we have some visualizations and able to detect issues.

**Comment by Lestat06** [comment]
This is confirmed

![image](https://user-images.githubusercontent.com/6232283/120359808-6402ec80-c308-11eb-88c4-7d67a7f66229.png)
![image](https://user-images.githubusercontent.com/6232283/120359755-58172a80-c308-11eb-8008-f2a85642c505.png)

**Comment by samarthdd** [comment]
Yes this is working as expected
