### ISSUE TITLE
Integrate Jaeger into the Kubernetes setup

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#61]
Currently Jaeger is being integrated into: srv1, srv2 and process , switch to "jaeger" branch to see the code. We need to:
1. Add the additional environment variables for these three services. env - JAEGER_AGENT_HOST=<jaeger-agent-host>  - JAEGER_AGENT_PORT=6831
2. Add an additional pod to act as the Jaeger instrument host, example code when running in docker below:  
     jaeger-agent:
    container_name: 'tracing.jaeger.agent'
    image: jaegertracing/all-in-one:latest
    networks:
        -  k8flow
    ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778/tcp"
        - "16686:16686"
        - "14268:14268"
        - "9411:9411"

**Comment by himanshu2464** [comment]
deploy jaeger-agent and all component as deployment and Service on setup and passing the env Variable in service .

**Comment by himanshu2464** [comment]
dockerbuild is failing for go-k8s-process from branch jaeger 

 ---> 5d73489d2559
Step 13/25 : COPY --from=builder /go/src/github.com/k8-proxy/go-k8s-process/sdk-rebuild-eval/libs/rebuild/linux/libglasswall.classic.so /usr/lib/libglasswall.classic.so
COPY failed: stat go/src/github.com/k8-proxy/go-k8s-process/sdk-rebuild-eval/libs/rebuild/linux/libglasswall.classic.so: file does not exist

**Comment by himanshu2464** [comment]
with jaeger-agent setup with branch jaeger, i am able to process the file and also i am getting the file back.

![image](https://user-images.githubusercontent.com/45463238/118184532-16a60480-b459-11eb-9d7c-1be40cc2652d.png)

**Comment by himanshu2464** [comment]
@mahnouman 
I tested it and it is working well.
should I update the helm charts deployment and add jaeger in the deployment.

**Comment by mahnouman** [comment]
Hi @himanshu2464 yes please do, thanks.

**Comment by samarthdd** [comment]
This is working on port 9001

**Comment by samarthdd** [comment]
Tested with new jaeger AMI  and its working

![image](https://user-images.githubusercontent.com/64204445/120382909-d80db680-c341-11eb-9f90-3aaa7e1dc459.png)

![image](https://user-images.githubusercontent.com/64204445/120382935-e0fe8800-c341-11eb-9883-9ea99010cfae.png)

**Comment by Lestat06** [comment]
@GINAGC this is ok

**Comment by GINAGC** [comment]
Thank you, moved to release.
