### ISSUE TITLE
High error rate on performance testing

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/go-k8s-infra#66]
10 % of files getting failed on every performance test run

The error is

fail: Glasswall.CloudProxy.Api.Controllers.RebuildController[0]
   [Web Application]:: Error Processing Timeout 'input' f9d5ac1e-626c-4a69-b012-8364adde060b exceeded 600s
   System.OperationCanceledException: The operation was canceled.

![image](https://user-images.githubusercontent.com/64204445/118529334-08a9f980-b761-11eb-89eb-9b0f816c930b.png)

![image](https://user-images.githubusercontent.com/64204445/118529344-0ba4ea00-b761-11eb-9e73-e4b331b599bc.png)

![image](https://user-images.githubusercontent.com/64204445/118529359-0f387100-b761-11eb-95ab-0618a0b39f1f.png)

**Comment by mahnouman** [comment]
@himanshu2464 @haitham911 Can Jaeger give us a clue here about where it got stuck?

**Comment by haitham911** [comment]
We can trace operations by jaeger .and see where the request fails

**Comment by himanshu2464** [comment]
yes we can trace operation , logs, event by jaeger and see where the request failed with information.

**Comment by GINAGC** [comment]
@samarthdd please retest this with the latest minio.

**Comment by GINAGC** [comment]
I am closing this one, since it is fixed on latest release.
