### ISSUE TITLE
Set the number of default concurrent processing pods to 20

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#67]
Change the default number of processing pods to 20 from the old value of 5. These values can be overridden anyway by an environment variable.

**Comment by himanshu2464** [comment]
I tested it by changing pod_count to 20 and all 20 pods of the process are running and the file is also processed.

![image](https://user-images.githubusercontent.com/45463238/118662713-d904fb00-b80d-11eb-99be-84c9ca504b81.png)

=================================================================================

![image](https://user-images.githubusercontent.com/45463238/118662903-ff2a9b00-b80d-11eb-8b90-f0aa434a57fa.png)

Done.
