### ISSUE TITLE
Testing with Folder2Folder (F2F)

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#68]
Implementation of a workflow where with a new release, we can trigger the workflow to test the full solution using the F2F setup as a test tool, reading the output of it, and save the results somewhere. Once we past this first phase we can work on enhancing the setup so it compare results to a previous run and so.

The F2F setup is here:
https://github.com/filetrust/cdr-plugin-folder-to-folder

**Updates:**
Sample files repo, not sure if it will be relevant to the task,  but anyway:
|https://github.com/k8-proxy/data-sets

**Comment by mahnouman** [comment]
@himanshu2464 please start with a manual run of that, then we scriptify it next.

**Comment by mahnouman** [comment]
Hi @azopat please advise once you are comfortable using F2F in testing, thanks.

**Comment by naderaly** [comment]
@mahnouman on testing the latest AMI https://github.com/filetrust/cdr-plugin-folder-to-folder/actions/runs/957895174
I faced an error trying to load cloud sdk IPs from AWS 
![image](https://user-images.githubusercontent.com/58347752/122869676-e5a8d180-d32c-11eb-994a-dee074d9a3e4.png)

**Comment by naderaly** [comment]
Tho I've tested an earlier AMI which worked as mentioned in docs here https://filetrust.github.io/cdr-plugin-folder-to-folder/docs/0.-introduction/ .
One more thing to mention there are some points/links in the documentation needs to be re reviewed for example the first 2 video links [here](https://filetrust.github.io/cdr-plugin-folder-to-folder/docs/6.-how-to-start/) point to the same video, who shall I contact to point it to? @MaNe2020 ?

**Comment by MaNe2020** [comment]
@naderaly yes me. We are in process of creating new UI, once that is ready I will include new videos and will probably remove the ones in question for now.
Pls let me know if you encountered any other issue or you feel some info is missing.

**Comment by naderaly** [comment]
@mahnouman , I processed 1000 file and those are the stats.
![image](https://user-images.githubusercontent.com/58347752/123016517-13445800-d3cb-11eb-8630-21b4f1fd3f33.png)
@MaNe2020 I faced a problem on trying to set IP manually to test specific icap server it keeps using the servers set in the auto scaling group which uses an old AMI , any idea how can I reslove this ?

**Comment by naderaly** [comment]
@mahnouman issue with choosing specific server to test has be resolved thanks to @MaNe2020.
Here's the status of a 1000 file run on an go based icap server 
![image](https://user-images.githubusercontent.com/58347752/123109779-cea4d500-d43b-11eb-902b-b4d9e8160f75.png)
