### ISSUE TITLE
compare text and metadata pod

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#72]
Develop a single use pod that can:
Compare the text and metadata from the original and CDRed files, and tell if the text of the file has been manipulated and upload results into minio.

Reference projects:
https://tika.apache.org/
https://github.com/apache/tika-docker

An additional value if possible to be investigates is to check if a file like pdf had active content (i.e. Macros or similar) and after processing, the active content is no longer exist, this might be possible by tika, but there is also a reference project here:
https://hub.docker.com/r/gkmr/pdf-tools

The development of this component might require the addition of a new queue.

Repo for this work:
https://github.com/k8-proxy/go-k8s-metadata

**Comment by haitham911** [comment]
I fished tika pod
in this repo https://github.com/k8-proxy/go-k8s-metadata
and now we can get metadat for source file ,and clean file  
and compare between the string. finally upload files to minio

**Comment by GINAGC** [comment]
this is not relevant, https://github.com/k8-proxy/go-k8s-metadata is now moved to glacier.
