### ISSUE TITLE
file-outcome header is not coming. here are the logs of GW Cloud SDK

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/go-k8s-infra#80]
![image](https://user-images.githubusercontent.com/64204445/120211864-0068b880-c24f-11eb-9812-43c239815c70.png)
![image](https://user-images.githubusercontent.com/64204445/120211954-0fe80180-c24f-11eb-9b04-ed1ec26def8b.png)

**Comment by GINAGC** [comment]
@samarthdd is this still an issue?

**Comment by GINAGC** [comment]
@Lestat06 please confirm if we can close.

**Comment by samarthdd** [comment]
This is fixed

I was involved in troubleshootig and later this was fixed by Patrick

**Comment by Lestat06** [comment]
@GINAGC yes tested also on postman and from pod logs
