### ISSUE TITLE
timeout  error

### ISSUE THREAD

**Issue by samarthdd** [k8-proxy/go-k8s-infra#83]
HTTPConnectionPool(host=,port=8080): Readtimed out. (read timeout=600)"

This can be replicated using cdr f2f plugin

Setup cdr f2f and set go-sdk-jeager IP

Run with 10 or 25 threads

<img width="1436" alt="Screenshot 2021-06-03 at 8 26 44 PM" src="https://user-images.githubusercontent.com/64204445/120666947-a401d500-c4aa-11eb-85d7-b7334342c8ce.png">

Here out of 16 failed files , 12 are valid files and throws timeout error

**Comment by GINAGC** [comment]
@samarthdd please retest.

**Comment by GINAGC** [comment]
this is not an issue.
