### ISSUE TITLE
Kubernetes dashboard

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#86]
To facilitate developers testing, please add Kubernetes dashboard into the setup.

**Comment by himanshu2464** [comment]
this is done and completed. and opening the dashboard on port number 9090 of the machine.

**Comment by GINAGC** [comment]
@naderaly please validate and document this. Thank you

**Comment by naderaly** [comment]
@GINAGC this is validated and added to readme in this PR
https://github.com/k8-proxy/go-k8s-infra/pull/102

**Comment by samarthdd** [comment]
This is fixed

![Uploading Screenshot 2021-06-30 at 6.35.39 PM.png…]()
