### ISSUE TITLE
minio and rabbitmq UI exposure

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-infra#87]
Please add to the readme file, what the developers need to do in order to expose minio and rabbitmq web UIs to the outside world, thanks

**Comment by himanshu2464** [comment]
@mahnouman  
I had a fix so that developer will not have to do anything to expose the minio and rabbitmq, I will add that in the deployment script.
will send an PR for this fix.

**Comment by himanshu2464** [comment]
this is done.
expose service as load balance
rabbitmq UI port : 15672
minio port: 9000
jaeger port: 9001

and working correctly in new build ami from develop branch.

**Comment by GINAGC** [comment]
@himanshu2464 please link the respective PRs on this issue. Thanks

**Comment by himanshu2464** [comment]
@GINAGC for this I have directly updated the deployment script in the vmware-script repo in develop branch, after changing the rabbitmq charts with the following PR.
https://github.com/k8-proxy/icap-infrastructure/pull/79.

**Comment by GINAGC** [comment]
@naderaly please validate and document this. Thank you

**Comment by naderaly** [comment]
@GINAGC this is validated and added to readme in this PR
https://github.com/k8-proxy/go-k8s-infra/pull/102

I've a question regarding filedrop secret/access keys tho where I asked @himanshu2464 about and will add the details when I have answer

**Comment by samarthdd** [comment]
This is fixed
