### ISSUE TITLE
Tune Kubernetes setup for t2.2xlarge instances

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/go-k8s-infra#96]

**Comment by himanshu2464** [comment]
this is completed and posted the new build AMIs after applying the fix.
and had also updated the readme file for services and port exposes.
Done.

**Comment by GINAGC** [comment]
@Lestat06, @samarthdd to test with the latest AMIs on develop and validate that no manual config steps are needed after deployment.

**Comment by Lestat06** [comment]
yes this is automated now.
